src/SIKeuanganGMITLanudPenfui/SIKeuanganGMITLanudPenfui.Web/Areas/Dashboard/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SIKeuanganGMITLanudPenfui.Domain.Entities;
using SIKeuanganGMITLanudPenfui.Domain.Repositories;
using SIKeuanganGMITLanudPenfui.Infrastructure.Authentication.Contracts;
using SIKeuanganGMITLanudPenfui.Web.Areas.Dashboard.Models.HomeModels;
using SIKeuanganGMITLanudPenfui.Web.Models;
using SIKeuanganGMITLanudPenfui.Web.Services.Toastr;

namespace SIKeuanganGMITLanudPenfui.Web.Areas.Dashboard.Controllers;

[Area("Dashboard")]
public class HomeController : Controller
{
    private readonly ISignInManager _signInManager;
    private readonly IRepositoriTransaksi _repositoriTransaksi;
    private readonly IToastrNotificationService _toastrNotificationService;

    public HomeController(
        ISignInManager signInManager,
        IRepositoriTransaksi repositoriTransaksi,
        IToastrNotificationService toastrNotificationService)
    {
        _signInManager = signInManager;
        _repositoriTransaksi = repositoriTransaksi;
        _toastrNotificationService = toastrNotificationService;
    }

    [Authorize(Roles = $"{UserRoles.Bendahara}, {UserRoles.Operator}")]
    public async Task<IActionResult> Index()
    {
        var daftarTransaksi = await _repositoriTransaksi.GetAll();

        return View(new IndexVM { DaftarTransaksi = daftarTransaksi });
    }

    [AllowAnonymous]
    [Route("[area]/[action]")]
    public IActionResult Login(string? returnUrl = null)
    {
        return View(new LoginVM
        {
            ReturnUrl = returnUrl ?? Url.Action("Index")!,
        });
    }

    [AllowAnonymous]
    [HttpPost]
    [Route("[area]/[action]")]
    public async Task<IActionResult> Login(LoginVM loginVM)
    {
        if(!ModelState.IsValid) return View(loginVM);

        var result = await _signInManager.Login(loginVM.Username, loginVM.Password, loginVM.RememberMe);

        if(result.IsFailure)
        {
            ModelState.AddModelError(string.Empty, result.Error.Message);
            return View(loginVM);
        }

        _toastrNotificationService.AddInformation($"Welcome {loginVM.Username}");

        return Redirect(loginVM.ReturnUrl);
    }

    [HttpPost]
    [Authorize(Roles = $"{UserRoles.Bendahara}, {UserRoles.Operator}")]
    public async Task<IActionResult> Logout()
    {
        await _signInManager.Logout();
        return RedirectToAction("Index", "Home", new {Area=""});
    }
}

src/SIKeuanganGMITLanudPenfui/SIKeuanganGMITLanudPenfui.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SIKeuanganGMITLanudPenfui.Domain.Entities;
using SIKeuanganGMITLanudPenfui.Domain.Repositories;
using SIKeuanganGMITLanudPenfui.Web.Models;
using SIKeuanganGMITLanudPenfui.Web.Models.HomeModels;
using SIKeuanganGMITLanudPenfui.Web.Services.Toastr;
using System.Diagnostics;

namespace SIKeuanganGMITLanudPenfui.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IRepositoriTransaksi _repositoriTransaksi;
        private readonly IRepositoriFeedBack _repositoriFeedBack;
        private readonly IToastrNotificationService _notificationService;
        private readonly IUnitOfWork _unitOfWork;

        public HomeController(
            ILogger<HomeController> logger,
            IRepositoriTransaksi repositoriTransaksi,
            IRepositoriFeedBack repositoriFeedBack,
            IToastrNotificationService notificationService,
            IUnitOfWork unitOfWork)
        {
            _logger = logger;
            _repositoriTransaksi = repositoriTransaksi;
            _repositoriFeedBack = repositoriFeedBack;
            _notificationService = notificationService;
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index()
        {
            var daftarTransaksi = await _repositoriTransaksi.GetAll();

            return View(new IndexVM { DaftarTransaksi = daftarTransaksi });
        }

        [HttpPost]
        public async Task<IActionResult> Index(IndexVM vm)
        {
            if (!ModelState.IsValid)
            {
                _notificationService.AddNotification(new ToastrNotification
                {
                    Title = "Kirim Pesan Gagal",
                    Message = "Terdapat error pada data yang dimasukkan",
                    Type = ToastrNotificationType.Error
                });

                return RedirectToAction(nameof(Index));
            }

            var feedBack = new FeedBack
            {
                Judul = vm.Judul,
                Nama = vm.Nama,
                Pesan = vm.Pesan,
                Tanggal = DateTime.Now,
                SudahDibaca = false
            };
            _repositoriFeedBack.Add(feedBack);
            var result = await _unitOfWork.SaveChangesAsync();
            if (result.IsFailure)
                _notificationService.AddNotification(new ToastrNotification
                {
                    Title = "Kirim Pesan Gagal",
                    Message = result.Error.Message,
                    Type = ToastrNotificationType.Error
                });
            else
                _notificationService.AddNotification(new ToastrNotification
                {
                    Title = "Kirim Pesan Berhasil",
                    Message = "Pesan feedback telah dikirim",
                    Type = ToastrNotificationType.Success
                });

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult StatusCode404()
        {
            return View();
        }

        public IActionResult StatusCode400()
        {
            return View();
        }

        public IActionResult StatusCode500()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/SIKeuanganGMITLanudPenfui/SIKeuanganGMITLanudPenfui.Web/ViewComponents/ChartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SIKeuanganGMITLanudPenfui.Web.Models;

namespace SIKeuanganGMITLanudPenfui.Web.ViewComponents;

public class ChartViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(ChartVM chartModel)
    {
        return View(chartModel);
    }
}

src/SIKeuanganGMITLanudPenfui/SIKeuanganGMITLanudPenfui.Web/Areas/Dashboard/Views/Home/Index.cshtml
@using SIKeuanganGMITLanudPenfui.Web.Models
@model IndexVM

@{
    ViewData["Title"] = "Home Page";
    var cultureInfo = new CultureInfo("id-ID");
}

<div class="row">
    <div class="col-xl-6 col-lg-12">
        <div class="card">
            <div class="card-body card-type-3">
                <div class="row">
                    <div class="col">
                        <h6 class="text-muted mb-0">
                            Total Penerimaan SD @DateTime.Now.ToString("dd MMMM yyyy", cultureInfo)
                        </h6>
@*                         <h4 class="font-weight-bold mb-0"> @Model.DaftarTransaksi.Where(t => t.Jenis == Jenis.Penerimaan).Sum(t => t.Jumlah).ToString("C2", cultureInfo)</h4>
 *@                    </div>
                    <div class="col-auto">
                        <div class="card-circle l-bg-green text-white">
                            <i class="fas fa-arrow-down"></i>
                        </div>
                    </div>
                </div>
                <p class="mt-0 mb-0 text-muted text-sm">
                    <h4 class="font-weight-bold mb-0"> @Model.DaftarTransaksi.Where(t => t.Jenis == Jenis.Penerimaan).Sum(t => t.Jumlah).ToString("C2", cultureInfo)</h4>
                    @* <span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 10%</span>
                    <span class="text-nowrap">Since last month</span> *@
                </p>
            </div>
        </div>
    </div>
    <div class="col-xl-6 col-lg-12">
        <div class="card">
            <div class="card-body card-type-3">
                <div class="row">
                    <div class="col">
                        <h6 class="text-muted mb-0">
                            Total Pengeluaran SD @DateTime.Now.ToString("dd MMMM yyyy", cultureInfo)
                        </h6>
@*                         <span class="font-weight-bold mb-0">1,562</span>
 *@                    </div>
                    <div class="col-auto">
                        <div class="card-circle l-bg-red text-white">
                            <i class="fas fa-arrow-up"></i>
                        </div>
                    </div>
                </div>
                <p class="mt-0 mb-0 text-muted text-sm">
                    <h4>
                        @Model.DaftarTransaksi.Where(t => t.Jenis == Jenis.Belanja).Sum(t => t.Jumlah).ToString("C2", cultureInfo)
                    </h4>
                    @* <span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 7.8%</span>
                    <span class="text-nowrap">Since last month</span> *@
                </p>
            </div>
        </div>
    </div>   
</div>

<div class="card">
    <div class="card-header">
        Penerimaan
    </div>
    <div class="card-body">
        <div class="row owl-carousel owl-theme grafik">
            <div class="col-12">
                <div class="card-body">
                    <vc:chart chart-model="@(new ChartVM
                    {
                        Label = "Penerimaan",
                          Data=new Dictionary<string, double>(
                            Model.TransaksiPerTanggal
                                 .Select(kv => new KeyValuePair<string, double>(
                                     kv.Key.ToString("dd/MM/yyyy"),
                                     kv.Value.Where(t => t.Jenis == Jenis.Penerimaan).Sum(t => t.Jumlah)))),
                        Type = ChartType.Line
                    })" />
                </div>
                <div class="card-footer d-flex justify-content-center">
                    Bulan @cultureInfo.DateTimeFormat.GetMonthName(DateTime.Now.Month)
                </div>
            </div>
            <div class="col-12">
                <div class="card-body">
                    <vc:chart chart-model="@(new ChartVM
                    {
                        Label = "Penerimaan",
                          Data=new Dictionary<string, double>(
                            Model.TransaksiPerBulan
                                 .Select(kv => new KeyValuePair<string, double>(
                                     cultureInfo.DateTimeFormat.GetAbbreviatedMonthName(kv.Key),
                                     kv.Value.Where(t => t.Jenis == Jenis.Penerimaan).Sum(t => t.Jumlah)))),
                        Type = ChartType.Line
                    })" />
                </div>
                <div class="card-footer d-flex justify-content-center">
                    Tahun @DateTime.Now.Year
                </div>
            </div>
            <div class="col-12">
                <div class="card-body">
                    <vc:chart chart-model="@(new ChartVM
                    {
                        Label = "Penerimaan",
                          Data=new Dictionary<string, double>(
                            Model.DaftarTransaksi
                                .Where(t => t.Jenis == Jenis.Penerimaan)
                                .GroupBy(t => t.Tanggal.Year)
                                .OrderBy(g => g.Key)
                                .Select(g => new KeyValuePair<string, double>(g.Key.ToString(), g.Sum(t => t.Jumlah)))),
                        Type = ChartType.Line
                    })" />
                </div>
            </div>
        </div>
    </div> 
</div>

<div class="card">
    <div class="card-header">
        Pengeluaran
    </div>
    <div class="card-body">
        <div class="row owl-carousel owl-theme grafik">
            <div class="col-12">
                <div class="card-body">
                    <vc:chart chart-model="@(new ChartVM
                    {
                        Label = "Pengeluaran",
                          Data=new Dictionary<string, double>(
                            Model.TransaksiPerTanggal
                                 .Select(kv => new KeyValuePair<string, double>(
                                     kv.Key.ToString("dd/MM/yyyy"),
                                     kv.Value.Where(t => t.Jenis == Jenis.Belanja).Sum(t => t.Jumlah)))),
                        Type = ChartType.Line
                    })" />
                </div>
                <div class="card-footer d-flex justify-content-center">
                    Bulan @cultureInfo.DateTimeFormat.GetMonthName(DateTime.Now.Month)
                </div>
            </div>
            <div class="col-12">
                <div class="card-body">
                    <vc:chart chart-model="@(new ChartVM
                    {
                        Label = "Pengeluaran",
                          Data=new Dictionary<string, double>(
                            Model.TransaksiPerBulan
                                 .Select(kv => new KeyValuePair<string, double>(
                                     cultureInfo.DateTimeFormat.GetAbbreviatedMonthName(kv.Key),
                                     kv.Value.Where(t => t.Jenis == Jenis.Belanja).Sum(t => t.Jumlah)))),
                        Type = ChartType.Line
                    })" />
                </div>
                <div class="card-footer d-flex justify-content-center">
                    Tahun @DateTime.Now.Year
                </div>
            </div>
            <div class="col-12">
                <div class="card-body">
                    <vc:chart chart-model="@(new ChartVM
                    {
                        Label = "Pengeluaran",
                          Data=new Dictionary<string, double>(
                            Model.DaftarTransaksi
                                .Where(t => t.Jenis == Jenis.Belanja)
                                .GroupBy(t => t.Tanggal.Year)
                                .OrderBy(g => g.Key)
                                .Select(g => new KeyValuePair<string, double>(g.Key.ToString(), g.Sum(t => t.Jumlah)))),
                        Type = ChartType.Line
                    })" />
                </div>
            </div>
        </div>
    </div> 
</div>

@section Scripts {
    <script type="text/javascript">
        $(function () {
            $('.grafik').owlCarousel({
                loop: true,
                autoPlay: true,
                nav: true,
                items: 1
            });
        });
    </script>
}

src/SIKeuanganGMITLanudPenfui/SIKeuanganGMITLanudPenfui.Web/Areas/Dashboard/Views/Home/Login.cshtml
@model LoginVM

@{
    Layout = null;
}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login - Sistem Keuangan GMIT Lanud Penfui</title>
    <link rel="stylesheet" href="~/css/app.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/datatables/datatables.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/dashboard.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/component.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/theme.css" asp-append-version="true" />
    @*     <link rel="stylesheet" href="~/SIKeuanganGMITLanudPenfui.Web.styles.css" asp-append-version="true" /> *@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>

<body>
    <div class="loader"></div>
    <div id="app">
        <section class="section">
            <div class="container mt-5">
                <div class="row">
                    <div class="col-12 col-md-10 offset-md-1 col-lg-10 offset-lg-1">
                        <div class="login-brand">
                            Sistem Informasi Keuangan Gereja
                        </div>
                        <div class="card card-primary">
                            <div class="row m-0">
                                <div class="col-12 col-md-12 col-lg-5 p-0">
                                    <div class="card-header text-center">
                                        <h4>Dashboard Admin</h4>
                                    </div>
                                    <div class="card-body">
                                        <form asp-action="Login" asp-controller="Home" asp-area="Dashboard" method="post">
                                            <div asp-validation-summary="ModelOnly" class="text-danger form-text"></div>

                                            <div class="form-group floating-addon">
                                                <label asp-for="@Model.Username">Username</label>
                                                <div class="input-group">
                                                    <div class="input-group-prepend">
                                                        <div class="input-group-text">
                                                            <i class="far fa-user"></i>
                                                        </div>
                                                    </div>
                                                    <input asp-for="@Model.Username" type="text" class="form-control" autofocus placeholder="Username">
                                                </div>
                                                <span class="text-danger form-text" asp-validation-for="@Model.Username"></span>
                                            </div>
                                            <div class="form-group floating-addon mb-5">
                                                <label asp-for="@Model.Password">Password</label>
                                                <div class="input-group">
                                                    <div class="input-group-prepend">
                                                        <div class="input-group-text">
                                                            <i class="fas fa-lock"></i>
                                                        </div>
                                                    </div>
                                                    <input asp-for="@Model.Password" type="password" class="form-control" placeholder="Password">
                                                </div>
                                                <span class="text-danger form-text" asp-validation-for="@Model.Password"></span>
                                            </div>

                                            <input asp-for="@Model.ReturnUrl" hidden />

                                            <div class="form-group text-center">
                                                <button type="submit" class="btn btn-lg btn-primary">
                                                    Login
                                                </button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <div class="col-12 col-md-12 col-lg-7 p-0">
                                    <div id="map" class="contact-map">
                                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1744.0123272579!2d123.65819668866342!3d-10.180670282136797!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2c568488aef228ff%3A0xa09c4a302e01718!2sGMIT%20Jemaat%20Lanud%20Eltari!5e0!3m2!1sid!2sid!4v1731592907275!5m2!1sid!2sid" width="100%" height="100%" style="border:0; border-radius: 10px" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="simple-footer">
                            Copyright &copy; Kerja Praktek 2024
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <script src="~/js/app.min.js" asp-append-version="true"></script>
    <script src="~/lib/datatables/datatables.min.js" asp-append-version="true"></script>
    <script src="~/js/datatables.js" asp-append-version="true"></script>
    <script src="~/js/dashboard.js" asp-append-version="true"></script>
</body>


@* <div class="login-container">
    <h1>Sistem Informasi Keuangan Gereja</h1>
    <form asp-action="Login" asp-controller="Home" asp-area="Dashboard" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger form-text"></div>

        <div class="form-group">
            <label asp-for="@Model.Username">Username</label>
            <input class="form-control" asp-for="@Model.Username">
            <span class="text-danger form-text" asp-validation-for="@Model.Username"></span>
        </div>
        <div class="form-group mt-3">
            <label asp-for="@Model.Password">Password</label>
            <input class="form-control" type="password" asp-for="@Model.Password">
            <span class="text-danger form-text" asp-validation-for="@Model.Password"></span>
        </div>

        <input asp-for="@Model.ReturnUrl" hidden/>
        <button type="submit" class="btn btn-primary mt-3">Login</button>
    </form>
</div> *@

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}