src/SIKeuanganGMITLanudPenfui/SIKeuanganGMITLanudPenfui.Web/Areas/Dashboard/Controllers/RealisasiController.cs
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SIKeuanganGMITLanudPenfui.Application.KasCQ.Commands.CreateKas;
using SIKeuanganGMITLanudPenfui.Application.KasCQ.Commands.EditKas;
using SIKeuanganGMITLanudPenfui.Application.Services;
using SIKeuanganGMITLanudPenfui.Application.TransaksiCQ.Commands.CreateBelanjaPanjar;
using SIKeuanganGMITLanudPenfui.Application.TransaksiCQ.Commands.CreateTransaksi;
using SIKeuanganGMITLanudPenfui.Application.TransaksiCQ.Commands.EditTransaksi;
using SIKeuanganGMITLanudPenfui.Application.TransaksiCQ.Commands.HapusTransaksi;
using SIKeuanganGMITLanudPenfui.Application.TransaksiCQ.Commands.MelunaskanPanjar;
using SIKeuanganGMITLanudPenfui.Domain.Entities;
using SIKeuanganGMITLanudPenfui.Domain.Enums;
using SIKeuanganGMITLanudPenfui.Domain.Repositories;
using SIKeuanganGMITLanudPenfui.Infrastructure.Services.FileUpload;
using SIKeuanganGMITLanudPenfui.Web.Areas.Dashboard.Models.RealisasiModels;
using SIKeuanganGMITLanudPenfui.Web.Models;
using SIKeuanganGMITLanudPenfui.Web.Services.Toastr;

namespace SIKeuanganGMITLanudPenfui.Web.Areas.Dashboard.Controllers;

[Area("Dashboard")]
public class RealisasiController : Controller
{
    private readonly IRepositoriTransaksi _repositoriTransaksi;
    private readonly IFileUploadService _fileUploadService;
    private readonly IFileService _fileService;
    private readonly ISender _sender;
    private readonly IRepositoriKas _repositoriKas;
    private readonly IUnitOfWork _unitOfWork;
    private readonly IToastrNotificationService _notificationService;

    public RealisasiController(
        IRepositoriTransaksi repositoriTransaksi,
        IFileUploadService fileUploadService,
        IFileService fileService,
        ISender sender,
        IRepositoriKas repositoriKas,
        IUnitOfWork unitOfWork,
        IToastrNotificationService notificationService)
    {
        _repositoriTransaksi = repositoriTransaksi;
        _fileUploadService = fileUploadService;
        _fileService = fileService;
        _sender = sender;
        _repositoriKas = repositoriKas;
        _unitOfWork = unitOfWork;
        _notificationService = notificationService;
    }

    [Authorize(Roles = $"{UserRoles.Bendahara}, {UserRoles.Operator}")]
    [Route("/[area]/[controller]/{jenis:required}/{tahun:int?}")]
    public async Task<IActionResult> Transaksi(Jenis jenis, int? tahun = null, DateOnly? start = null, DateOnly? end = null)
    {
        tahun ??= DateTime.Now.Year;

        if (start is null || start.Value.Year != tahun)
            start = new DateOnly(tahun.Value, 1, 1);

        if (end is null || end.Value.Year != tahun)
            end = new DateOnly(tahun.Value, 12, 31);

        var daftarTransaksi = (await _repositoriTransaksi.GetAllByTahun(tahun.Value, jenis))
            .Where(t => DateOnly.FromDateTime(t.Tanggal) >= start.Value && DateOnly.FromDateTime(t.Tanggal) <= end.Value)
            .ToList();

        return View(new TransaksiVM
        {
            Tahun = tahun.Value,
            Jenis = jenis,
            DaftarTransaksi = daftarTransaksi.OrderBy(p => p.Tanggal).ToList(),
            Start = start.Value,
            End = end.Value
        });
    }

    [Authorize(Roles = $"{UserRoles.Bendahara}, {UserRoles.Operator}")]
    [Route("/[area]/[controller]/{jenis:required}/{tahun:int}/[action]")]
    public IActionResult Tambah(Jenis jenis, int tahun)
    {
        return View(new TambahVM
        {
            Jenis = jenis,
            Tahun = tahun
        });
    }

    [Authorize(Roles = $"{UserRoles.Bendahara}, {UserRoles.Operator}")]
    [HttpPost]
    [Route("/[area]/[controller]/{jenis:required}/{tahun:int}/[action]")]
    public async Task<IActionResult> Tambah([FromRoute] Jenis jenis, [FromRoute] int tahun, [FromForm] TambahVM vm)
    {
        if (!ModelState.IsValid) return View(vm);

        if (jenis != vm.Jenis || tahun != vm.Tahun) return BadRequest();

        if (vm.Tanggal.Year != vm.Tahun)
        {
            ModelState.AddModelError(nameof(TambahVM.Tanggal), "Tahun salah");
            return View(vm);
        }

        var fileBukti = await _fileUploadService.UploadFile<TambahVM>(
            vm.FileBukti,
            "/filebukti",
            [".pdf", ".docx", ".jpg", ".jpeg"],
            long.MinValue,
            long.MaxValue);

        if (fileBukti.IsFailure)
        {
            ModelState.AddModelError(nameof(TambahVM.FileBukti), fileBukti.Error.Message);
            return View(vm);
        }

        var command = new CreateTransaksiCommand(
            vm.Tanggal,
            vm.Jam,
            vm.Uraian,
            vm.Jumlah,
            fileBukti.Value,
            vm.NomorBukti,
            vm.Jenis,
            vm.IdAkun,
            vm.IdKas);

        var result = await _sender.Send(command);
        if (result.IsFailure)
        {
            ModelState.AddModelError(string.Empty, result.Error.Message);
            return View(vm);
        }

        _notificationService.AddSuccess("Transaksi baru sukses ditambahkan");

        return RedirectToAction(nameof(Transaksi), new { jenis, tahun });
    }

    [Authorize(Roles = $"{UserRoles.Bendahara}, {UserRoles.Operator}")]
    [Route("/[area]/[controller]/{jenis:required}/{tahun:int}/[action]/{id:int}")]
    public async Task<IActionResult> Edit(Jenis jenis, int tahun, int id)
    {
        var transaksi = await _repositoriTransaksi.Get(id);
        if (transaksi is null) return NotFound();
        if (transaksi.Tanggal.Year != tahun) return BadRequest();

        return View(new EditVM
        {
            IdTransaksi = id,
            NomorBukti = transaksi.NomorBukti!,
            Uraian = transaksi.Uraian,
            IdAkun = transaksi.Akun.Id,
            Jenis = jenis,
            Tahun = tahun
        });
    }

    [Authorize(Roles = $"{UserRoles.Bendahara}, {UserRoles.Operator}")]
    [HttpPost]
    [Route("/[area]/[controller]/{jenis:required}/{tahun:int}/[action]/{id:int}")]
    public async Task<IActionResult> Edit([FromRoute] Jenis jenis, [FromRoute] int tahun, [FromRoute] int id, [FromForm] EditVM vm)
    {
        if (!ModelState.IsValid) return View(vm);

        if (jenis != vm.Jenis || tahun != vm.Tahun || vm.IdTransaksi != id) return BadRequest();

        var fileBukti = await _fileUploadService.UploadFile<TambahVM>(
           vm.FileBukti,
           "/filebukti",
           [".pdf", ".docx", ".jpg", ".jpeg"],
           long.MinValue,
           long.MaxValue);

        if (fileBukti.IsFailure)
        {
            ModelState.AddModelError(nameof(TambahVM.FileBukti), fileBukti.Error.Message);
            return View(vm);
        }

        var command = new EditTransaksiCommand(vm.IdTransaksi, vm.Uraian, fileBukti.Value, vm.NomorBukti, vm.IdAkun);
        var result = await _sender.Send(command);

        if (result.IsFailure)
        {
            ModelState.AddModelError(string.Empty, result.Error.Message);
            return View(vm);
        }

        _notificationService.AddSuccess("Transaksi sukses diubah");

        return RedirectToAction(nameof(Transaksi), new { tahun, jenis });
    }

    [Authorize(Roles = $"{UserRoles.Bendahara}, {UserRoles.Operator}")]
    [HttpPost]
    [Route("/[area]/[controller]/{jenis:required}/{tahun:int}/[action]/{id:int}")]
    public async Task<IActionResult> Hapus(Jenis jenis, int tahun, int id)
    {
        var transaksi = await _repositoriTransaksi.Get(id);
        if (transaksi is null) return NotFound();

        var command = new HapusTransaksiCommand(id);
        var result = await _sender.Send(command);
        if (result.IsFailure)
        {
            _notificationService.AddNotification(new ToastrNotification
            {
                Title = $"Hapus {jenis} gagal",
                Message = result.Error.Message,
                Type = ToastrNotificationType.Error
            });
        }
        else
        {
            _notificationService.AddNotification(new ToastrNotification
            {
                Title = $"Hapus {jenis} Berhasil",
                Message = $"{jenis} '{transaksi.Uraian}' berhasil dihapus",
                Type = ToastrNotificationType.Success
            });
        }

        return RedirectToAction(nameof(Transaksi), new {tahun, jenis});
    }

    [Authorize(Roles = $"{UserRoles.Bendahara}, {UserRoles.Operator}")]
    [Route("/[area]/[controller]/[action]")]
    public async Task<IActionResult> Kas()
    {
        var daftarKas = await _repositoriKas.GetAll();
        return View(daftarKas);
    }

    [Authorize(Roles = $"{UserRoles.Bendahara}")]
    [Route("/[area]/[controller]/Kas/Tambah")]
    public IActionResult TambahKas()
    {
        return View(new TambahKasVM());
    }

    [Authorize(Roles = $"{UserRoles.Bendahara}")]
    [HttpPost]
    [Route("/[area]/[controller]/Kas/Tambah")]
    public async Task<IActionResult> TambahKas(TambahKasVM vm)
    {
        if (!ModelState.IsValid) return View(vm);

        var command = new CreateKasCommand(vm.Uraian, vm.Saldo, vm.Keterangan);
        var result = await _sender.Send(command);
        if (result.IsFailure)
        {
            ModelState.AddModelError(string.Empty, result.Error.Message);
            return View(vm);
        }

        _notificationService.AddSuccess("Kas baru sukses ditambahkan");

        return RedirectToAction(nameof(Kas));
    }

    [Authorize(Roles = $"{UserRoles.Bendahara}")]
    [Route("/[area]/[controller]/Kas/Edit/{id:int}")]
    public async Task<IActionResult> EditKas(int id)
    {
        var kas = await _repositoriKas.Get(id);
        if (kas is null) return NotFound();

        return View(new EditKasVM
        {
            IdKas = kas.Id,
            Uraian = kas.Uraian,
            Keterangan = kas.Keterangan,
        });
    }

    [Authorize(Roles = $"{UserRoles.Bendahara}")]
    [HttpPost]
    [Route("/[area]/[controller]/Kas/Edit/{id:int}")]

src/SIKeuanganGMITLanudPenfui/SIKeuanganGMITLanudPenfui.Web/Areas/Dashboard/Views/Realisasi/EditKas.cshtml
@model EditKasVM

@{
    ViewData["Title"] = "Realisasi | Tambah Kas";
}

<!-- Breadcrumb -->
<div class="row" style="justify-content: center;">
    <div class="col-12 col-md-6 col-lg-6" style="padding: 0;">
        <partial name="_BreadcrumbPartial" />
    </div>
</div>

<div class="section-body">
    <div class="row" style="justify-content: center;">
        <div class="col-12 col-md-6 col-lg-6">
            <div class="card card-danger">
                <div class="card-header">
                    <h4>Edit Kas</h4>
                </div>
                <form asp-action="@nameof(RealisasiController.EditKas)" asp-route-id="@Model.IdKas">
                    <div class="card-body">
                        <div asp-validation-summary="ModelOnly"></div>

                        <div class="form-group mb-0">
                            <label asp-for="@Model.Uraian" class="form-label"></label>
                            <input asp-for="@Model.Uraian" class="form-control" />
                            <span asp-validation-for="@Model.Uraian"></span>
                        </div>

                        <div class="form-group">
                            <label asp-for="@Model.Keterangan" class="form-label"></label>
                            <input asp-for="@Model.Keterangan" class="form-control" placeholder="Uraian..." autofocus />
                            <span asp-validation-for="@Model.Keterangan"></span>
                        </div>

                        <input asp-for="@Model.IdKas" readonly hidden />                        
                    </div>
                    <div class="card-footer text-right">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                        <a asp-action="@nameof(RealisasiController.Kas)" class="btn btn-danger">Batal</a>
                    </div>
                </form>                
            </div>
        </div>
    </div>
</div>

src/SIKeuanganGMITLanudPenfui/SIKeuanganGMITLanudPenfui.Web/Areas/Dashboard/Views/Realisasi/Kas.cshtml
@using SIKeuanganGMITLanudPenfui.Infrastructure.Authentication.Contracts
@model List<Kas>

@inject ISignInManager SignInManager

@{
    ViewData["Title"] = "Realisasi | Kas";
    var cultureInfo = new CultureInfo("id-ID");
    var user = (await SignInManager.GetUser())!;
}

<!-- Breadcrumb -->
<div class="row">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Realisasi</a></li>
            <li class="breadcrumb-item"><a asp-area="Dashboard" asp-controller="Realisasi" asp-action="@nameof(RealisasiController.Kas)"></a>Kas</li>
        </ol>
    </nav>
</div>

<div class="card card-primary">
    <div class="card-header">
        <h4>Kas</h4>
    </div>
    <div class="padding-20">
        @if (user.Role == UserRoles.Bendahara)
        {
            <div class="d-flex justify-content-start ml-auto mb-2">
                <div class="mb-0">
                    <a asp-action="@nameof(RealisasiController.TambahKas)" class="btn btn-primary" data-toggle="tooltip" title="Tambah Kas"><i class="fas fa-plus"></i> Tambah</a>
                </div>
            </div>
        }

        <div class="table-responsive">
            <table class="table table-striped table-hover" id="table-akun-1">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Uraian</th>
                        <th>Keterangan</th>
                        <th>Saldo</th>
                        <th>Terakhir Berubah</th>
                        @if (user.Role == UserRoles.Bendahara)
                        {
                            <th>Aksi</th>
                        }
                    </tr>
                </thead>
                <tbody>
                    @{
                        var no = 1;
                    }

                    @foreach (var kas in Model)
                    {
                        <tr>
                            <td>@no</td>
                            <td>@kas.Uraian</td>
                            <td>@kas.Keterangan</td>
                            <td>@kas.Saldo.ToString("C2", cultureInfo)</td>
                            @if (kas.TanggalDiubah is not null)
                            {
                                <td>
                                    @kas.TanggalDiubah.Value.ToString(cultureInfo.DateTimeFormat.ShortDatePattern, cultureInfo)
                                    @kas.TanggalDiubah.Value.ToString(cultureInfo.DateTimeFormat.LongTimePattern, cultureInfo)
                                </td>
                            }
                            else
                            {
                                <td></td>
                            }

                            @if (user.Role == UserRoles.Bendahara)
                            {
                                <td>
                                    <a asp-action="@nameof(RealisasiController.EditKas)" asp-route-id="@kas.Id" class="btn btn-primary">Edit</a>
                                    <form asp-action="@nameof(RealisasiController.HapusKas)" asp-route-id="@kas.Id" style="display:inline">
                                        <button type="button" class="btn btn-danger btn-action" data-toggle="modal" data-target="#basicModal2"
                                                data-url="@Url.Action("HapusKas", new { id = kas.Id })"
                                                title="Hapus">
                                            <i class="fas fa-trash"></i>
                                        </button>
                                    </form>
                                </td>
                            }
                        </tr>
                        no++;
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

src/SIKeuanganGMITLanudPenfui/SIKeuanganGMITLanudPenfui.Web/Areas/Dashboard/Views/Realisasi/Panjar.cshtml
@model PanjarVM

@{
    ViewData["Title"] = $"Realisasi | Panjar";
    var cultureInfo = new CultureInfo("id-ID");
}

<!-- Breadcrumb -->
<div class="row">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Realisasi</a></li>
            <li class="breadcrumb-item"><a asp-area="Dashboard" asp-controller="Realisasi" asp-action="@nameof(RealisasiController.Panjar)"></a>Panjar</li>
        </ol>
    </nav>
</div>

<div class="card card-primary">
    <div class="card-header">
        <h4>Realisasi - Panjar - @Model.Tahun</h4>
    </div>
    <div class="card-body pt-1">
        <div class="row d-flex justify-content-start ml-auto mb-2">
            <div class="col-auto p-0 mt-1">
                <a asp-action="@nameof(RealisasiController.TambahPanjar)" asp-route-tahun="@Model.Tahun" class="btn btn-primary"><i class="fas fa-plus"></i> Tambah</a>
            </div>

            <div class="col-9 d-flex justify-content-center p-l-100">
                <div class="row w-100">
                    <div class="col-2 text-right align-content-center">
                        <label class="form-label m-0">Start</label>
                    </div>
                    <div class="col-10 p-0">
                        <input asp-for="@Model.Start" type="date" class="form-control" id="start" />
                    </div>
                </div>
                <div class="row w-100 pl-4">
                    <div class="col-2 text-right align-content-center">
                        <label class="form-label m-0">End</label>
                    </div>
                    <div class="col-10 pl-0">
                        <input asp-for="@Model.End" type="date" class="form-control" id="end" />
                    </div>
                </div>
                <div class="align-content-end pb-1 pl-2">
                    <button class="btn btn-secondary buttons-copy button-html5" id="filter">Filter</button>
                </div>
            </div>

            <div class="col-auto ml-auto">
                <select id="tahun" class="form-control">
                    @foreach (var tahun in Enumerable.Range(DateTime.Now.Year - 5, 11))
                    {
                        @if (tahun == Model.Tahun)
                        {
                            <option selected value="@tahun">@tahun</option>
                        }
                        else
                        {
                            <option value="@tahun">@tahun</option>
                        }
                    }
                </select>
            </div>
        </div>

        <div class="table-responsive">
            <table class="table table-striped table-hover nowrap" id="table-akun">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Tanggal</th>
                        <th style="width: 150px">Akun</th>
                        <th style="width: 250px">Uraian</th>
                        <th>Kas</th>
                        <th>Jumlah</th>
                        <th style="width: 100px">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        var no = 1;
                    }
                    @foreach (var transaksi in Model.DaftarTransaksi)
                    {
                        <tr>
                            <td>@no</td>
                            <td>@transaksi.Tanggal.ToString("dd/MM/yyyy HH:mm", cultureInfo)</td>
                            <td>@transaksi.Akun.KodeAkun @transaksi.Akun.Uraian</td>
                            <td>@transaksi.Uraian</td>
                            <td>@transaksi.Kas.Uraian</td>
                            <td class="text-right">@transaksi.Jumlah.ToString("C2", cultureInfo)</td>
                            <td>
                                <a asp-action="@nameof(RealisasiController.EditPanjar)"
                                   asp-route-tahun="@Model.Tahun"
                                   asp-route-id="@transaksi.Id" class="btn btn-primary">Edit</a>
                                <a asp-action="@nameof(RealisasiController.Lunaskan)"
                                   asp-route-tahun="@Model.Tahun"
                                   asp-route-id="@transaksi.Id" class="btn btn-primary">Lunaskan</a>
                                <form asp-action="@nameof(RealisasiController.HapusPanjar)"
                                      asp-route-tahun="@Model.Tahun"
                                      asp-route-id="@transaksi.Id" style="display:inline">
                                    <button type="button" class="btn btn-danger btn-action" data-toggle="modal" data-target="#basicModal2"
                                            data-url="@Url.Action("HapusPanjar", new { tahun = Model.Tahun, id = transaksi.Id })"
                                            title="Hapus">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                        no++;
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="padding-20">
    </div>
</div>


@section Scripts {
    <partial name="_BreadcrumbScriptPartial" />

    <script type="text/javascript">
        const selectTahun = $('select#tahun');

        const url = '@Url.Action(nameof(RealisasiController.Panjar))';

        $(selectTahun).on('change', function () {
            const tahun = $(selectTahun).val();

            location.href = `${url}/${tahun}`;
        });
    </script>

    <script type="text/javascript">
        const inputStart = $("input#start");
        const inputEnd = $("input#end");
        const btnFilter = $("button#filter");

        const url2 = '@Url.Action(nameof(RealisasiController.Transaksi), new { tahun = Model.Tahun })';

        $(btnFilter).on("click", function () {
            const start = inputStart.val();
            const end = inputEnd.val();

            location.href = `${url2}?start=${start}&end=${end}`;
        });
    </script>
}

src/SIKeuanganGMITLanudPenfui/SIKeuanganGMITLanudPenfui.Web/Areas/Dashboard/Views/Realisasi/Transaksi.cshtml
@model TransaksiVM

@{
    ViewData["Title"] = $"Realisasi | {Model.Jenis}";
    var cultureInfo = new CultureInfo("id-ID");
}

<!-- Breadcrumb -->
<div class="row">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Realisasi</a></li>
            <li class="breadcrumb-item"><a asp-area="Dashboard" asp-controller="Realisasi" asp-action="@nameof(RealisasiController.Transaksi)" asp-route-jenis="@Model.Jenis"></a>@Model.Jenis</li>
        </ol>
    </nav>
</div>

<div class="card card-primary">
    <div class="card-header">
        <h4>Realisasi - @Model.Jenis.ToString() - @Model.Tahun</h4>
    </div>
    <div class="card-body pt-1">
        <div class="row d-flex justify-content-start ml-auto mb-2">
            <div class="col-auto p-0 mt-1">
                <a asp-action="@nameof(RealisasiController.Tambah)" asp-route-jenis="@Model.Jenis" asp-route-tahun="@Model.Tahun" class="btn btn-primary"><i class="fas fa-plus"></i> Tambah</a>
            </div>

            <div class="col-9 d-flex justify-content-center p-l-100">
                <div class="row w-100">
                    <div class="col-2 text-right align-content-center">
                        <label class="form-label m-0">Start</label>
                    </div>
                    <div class="col-10 p-0">
                        <input asp-for="@Model.Start" type="date" class="form-control" id="start" />

                    </div>
                </div>
                <div class="row w-100 pl-4">
                    <div class="col-2 text-right align-content-center">
                        <label class="form-label m-0">End</label>
                    </div>
                    <div class="col-10 pl-0">
                        <input asp-for="@Model.End" type="date" class="form-control" id="end" />
                    </div>
                </div>
                <div class="align-content-end pb-1 pl-2">
                    <button class="btn btn-secondary buttons-copy button-html5" id="filter">Filter</button>
                </div>
            </div>            

            <div class="col-auto ml-auto">
                <select id="tahun" class="form-control">
                    @foreach (var tahun in Enumerable.Range(DateTime.Now.Year - 5, 11))
                    {
                        @if (tahun == Model.Tahun)
                        {
                            <option selected value="@tahun">@tahun</option>
                        }
                        else
                        {
                            <option value="@tahun">@tahun</option>
                        }
                    }
                </select>
            </div>
        </div>

        @* <div class="row mb-3 justify-content-center">
            <div class="col-5">
                <label class="form-label">Start</label>
                <input asp-for="@Model.Start" type="date" class="form-control" id="start" />
            </div>
            <div class="col-5">
                <label class="form-label">End</label>
                <input asp-for="@Model.End" type="date" class="form-control" id="end" />
            </div>
            <div class="col-2 align-content-end pb-1">
                <button class="btn btn-primary" id="filter">Filter</button>
            </div>
        </div> *@

        <div class="table-responsive">
            <table class="table table-striped table-hover nowrap" id="table-akun">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Tanggal</th>
                        <th style="width: 150px">Akun</th>
                        <th style="width: 250px">Uraian</th>
                        <th>Kas</th>
                        <th>File Bukti</th>
                        <th>Nomor Bukti</th>
                        <th>Jumlah</th>
                        <th>Saldo Terakhir</th>
                        <th style="width: 100px">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        var no = 1;
                    }
                    @foreach (var transaksi in Model.DaftarTransaksi)
                    {
                        <tr>
                            <td>@no</td>
                            <td>@transaksi.Tanggal.ToString("dd/MM/yyyy HH:mm", cultureInfo)</td>
                            <td>@transaksi.Akun.KodeAkun @transaksi.Akun.Uraian</td>
                            <td>@transaksi.Uraian</td>
                            <td>@transaksi.Kas.Uraian</td>
                            <td>
                                <a href="@transaksi.FileBukti.ToString()">File Bukti</a>
                            </td>
                            <td>@transaksi.NomorBukti</td>
                            <td class="text-right">@transaksi.Jumlah.ToString("C2", cultureInfo)</td>
                            <td class="text-right">@transaksi.SaldoKas.ToString("C2", cultureInfo)</td>
                            <td>
                                <a asp-action="@nameof(RealisasiController.Edit)" asp-route-jenis="@Model.Jenis" asp-route-tahun="@Model.Tahun"
                                   asp-route-id="@transaksi.Id" class="btn btn-primary">Edit</a>
                                <form asp-action="@nameof(RealisasiController.Hapus)" asp-route-jenis="@Model.Jenis" asp-route-tahun="@Model.Tahun"
                                      asp-route-id="@transaksi.Id" style="display:inline">
                                    <button type="button" class="btn btn-danger btn-action" data-toggle="modal" data-target="#basicModal2"
                                            data-url="@Url.Action("Hapus", new { jenis = Model.Jenis, tahun = Model.Tahun, id = transaksi.Id })"
                                            title="Hapus">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                        no++;
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="padding-20">
        

       
    </div>
</div>


@section Scripts {
    <partial name="_BreadcrumbScriptPartial" />

    <script type="text/javascript">
        const selectTahun = $('select#tahun');

        const url = '@Url.Action(nameof(RealisasiController.Transaksi), new { jenis = Model.Jenis })';

        $(selectTahun).on('change', function () {
            const tahun = $(selectTahun).val();

            location.href = `${url}/tahun=${tahun}`;
        });
    </script>

    <script type="text/javascript">
        const inputStart = $("input#start");
        const inputEnd = $("input#end");
        const btnFilter = $("button#filter");

        const url2 = '@Url.Action(nameof(RealisasiController.Transaksi), new { jenis = Model.Jenis, tahun=Model.Tahun })';

        $(btnFilter).on("click", function () {
            const start = inputStart.val();
            const end = inputEnd.val();

            location.href = `${url2}?start=${start}&end=${end}`;
        });
    </script>
}