src/SIKeuanganGMITLanudPenfui/SIKeuanganGMITLanudPenfui.Web/Areas/Dashboard/Controllers/FeedBackController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SIKeuanganGMITLanudPenfui.Domain.Entities;
using SIKeuanganGMITLanudPenfui.Domain.Repositories;
using SIKeuanganGMITLanudPenfui.Web.Models;
using SIKeuanganGMITLanudPenfui.Web.Services.Toastr;

namespace SIKeuanganGMITLanudPenfui.Web.Areas.Dashboard.Controllers;

[Area("Dashboard")]
[Authorize(Roles = $"{UserRoles.Bendahara}, {UserRoles.Operator}")]
public class FeedBackController : Controller
{
    private readonly IRepositoriFeedBack _repositoriFeedBack;
    private readonly IUnitOfWork _unitOfWork;
    private readonly IToastrNotificationService _notificationService;

    public FeedBackController(
        IRepositoriFeedBack repositoriFeedBack,
        IUnitOfWork unitOfWork,
        IToastrNotificationService notificationService)
    {
        _repositoriFeedBack = repositoriFeedBack;
        _unitOfWork = unitOfWork;
        _notificationService = notificationService;
    }

    public async Task<IActionResult> Index()
    {
        var daftarFeedBack = await _repositoriFeedBack.GetAll();

        return View(daftarFeedBack);
    }

    [HttpPost] 
    public async Task<IActionResult> Hapus(int id)
    {
        var feedBack = await _repositoriFeedBack.Get(id);
        if (feedBack is null) return NotFound();

        _repositoriFeedBack.Delete(feedBack);
        var result = await _unitOfWork.SaveChangesAsync();
        if (result.IsFailure)
            _notificationService.AddNotification(new ToastrNotification
            {
                Title = "Hapus Umpan Balik Gagal",
                Message = result.Error.Message,
                Type = ToastrNotificationType.Error
            });
        else
            _notificationService.AddNotification(new ToastrNotification
            {
                Title = "Hapus Umpan Balik Berhasil",
                Type = ToastrNotificationType.Success
            });

        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    public async Task<IActionResult> MarkAsRead(int id, string? url = null)
    {
        url ??= Url.Action(nameof(Index))!;

        var feedBack = await _repositoriFeedBack.Get(id);
        if (feedBack is null) return NotFound();

        feedBack.SudahDibaca = true;
        _repositoriFeedBack.Update(feedBack);

        var result = await _unitOfWork.SaveChangesAsync();
        if (result.IsFailure)
            _notificationService.AddNotification(new ToastrNotification
            {
                Title = "Umpan Balik Gagal Ditandai Sudah Dibaca",
                Message = result.Error.Message,
                Type = ToastrNotificationType.Error
            });
        else
            _notificationService.AddNotification(new ToastrNotification
            {
                Title = "Umpan Balik Ditandai Sudah Dibaca",
                Type = ToastrNotificationType.Success
            });

        return Redirect(url);
    }

    [HttpPost]
    public async Task<IActionResult> MarkAllAsRead(string? url = null)
    {
        url ??= Url.Action(nameof(Index))!;

        var daftarFeedBack = await _repositoriFeedBack.GetAllUnread();

        foreach(var feedBack in daftarFeedBack)
        {
            feedBack.SudahDibaca = true;
            _repositoriFeedBack.Update(feedBack);
        }

        var result = await _unitOfWork.SaveChangesAsync();
        if (result.IsFailure)
            _notificationService.AddNotification(new ToastrNotification
            {
                Title = "Umpan Balik Gagal Ditandai Sudah Dibaca",
                Message = result.Error.Message,
                Type = ToastrNotificationType.Error
            });
        else
            _notificationService.AddNotification(new ToastrNotification
            {
                Title = "Umpan Balik Ditandai Sudah Dibaca",
                Type = ToastrNotificationType.Success
            });

        return Redirect(url);
    }
}

src/SIKeuanganGMITLanudPenfui/SIKeuanganGMITLanudPenfui.Web/Areas/Dashboard/Controllers/RAPBJController.cs
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SIKeuanganGMITLanudPenfui.Application.RAPBJCQ.Commands.AddAllAkun;
using SIKeuanganGMITLanudPenfui.Application.RAPBJCQ.Commands.CreateDetailRAPBJ;
using SIKeuanganGMITLanudPenfui.Application.RAPBJCQ.Commands.CreateRAPBJ;
using SIKeuanganGMITLanudPenfui.Application.RAPBJCQ.Commands.DeleteDetailRAPBJ;
using SIKeuanganGMITLanudPenfui.Application.RAPBJCQ.Commands.DeleteRAPBJ;
using SIKeuanganGMITLanudPenfui.Application.RAPBJCQ.Commands.EditDetailRAPBJ;
using SIKeuanganGMITLanudPenfui.Domain.Entities;
using SIKeuanganGMITLanudPenfui.Domain.Enums;
using SIKeuanganGMITLanudPenfui.Domain.Repositories;
using SIKeuanganGMITLanudPenfui.Domain.ValueObjects;
using SIKeuanganGMITLanudPenfui.Web.Areas.Dashboard.Models.RAPBJModels;
using SIKeuanganGMITLanudPenfui.Web.Models;
using SIKeuanganGMITLanudPenfui.Web.Services.Toastr;

namespace SIKeuanganGMITLanudPenfui.Web.Areas.Dashboard.Controllers;

[Area("Dashboard")]
[Authorize(Roles = UserRoles.Bendahara)]
public class RAPBJController : Controller
{
    private readonly IRepositoriRAPBJ _repositoriRAPBJ;
    private readonly IRepositoriDetailRAPBJ _repositoriDetailRAPBJ;
    private readonly IRepositoriAkun _repositoriAkun;
    private readonly IRepositoriJenisAkun _repositoriJenisAkun;
    private readonly ISender _sender;
    private readonly IUnitOfWork _unitOfWork;
    private readonly IToastrNotificationService _notificationService;

    public RAPBJController(
        IRepositoriRAPBJ repositoriRAPBJ,
        IRepositoriDetailRAPBJ repositoriDetailRAPBJ,
        IRepositoriAkun repositoriAkun,
        IRepositoriJenisAkun repositoriJenisAkun,
        IUnitOfWork unitOfWork,
        ISender sender,
        IToastrNotificationService notificationService)
    {
        _repositoriRAPBJ = repositoriRAPBJ;
        _repositoriDetailRAPBJ = repositoriDetailRAPBJ;
        _repositoriAkun = repositoriAkun;
        _repositoriJenisAkun = repositoriJenisAkun;
        _unitOfWork = unitOfWork;
        _sender = sender;
        _notificationService = notificationService;
    }

    [Route("[area]/[controller]/{jenis}/{tahun:int?}")]
    public async Task<IActionResult> Index(Jenis jenis, int? tahun = null)
    {
        tahun ??= DateTime.Now.Year;
        var rTahun = Tahun.Create(tahun.Value);
        if (rTahun.IsFailure) return BadRequest();

        var rapbj = await _repositoriRAPBJ.Get(rTahun.Value);

        return View(new IndexVM
        {
            Tahun = tahun.Value,
            Jenis = jenis,
            RAPBJ = rapbj
        });
    }

    [Route("[area]/[controller]/{jenis}/{tahun:int}/[action]")]
    public async Task<IActionResult> TambahDetailRAPBJ(Jenis jenis, int tahun)
    {
        var rTahun = Tahun.Create(tahun);
        if (rTahun.IsFailure) return BadRequest();

        var rapbj = await _repositoriRAPBJ.Get(rTahun.Value);
        if (rapbj is null) return NotFound();

        return View(new TambahDetailRAPBJVM
        {
            Tahun = tahun,
            Jenis = jenis
        });
    }

    [HttpPost]
    [Route("[area]/[controller]/{jenis}/{tahun:int}/[action]")]
    public async Task<IActionResult> TambahDetailRAPBJ(
        [FromRoute] Jenis jenis,
        [FromRoute] int tahun,
        [FromForm] TambahDetailRAPBJVM vm)
    {
        if (!ModelState.IsValid)
            return View(vm);

        if (jenis != vm.Jenis || tahun != vm.Tahun) return BadRequest();

        var command = new CreateDetailRAPBJCommand(vm.Tahun, vm.IdAkun, vm.Volume, vm.Satuan, vm.HargaSatuan);
        var result = await _sender.Send(command);
        if(result.IsFailure)
        {
            ModelState.AddModelError(string.Empty, result.Error.Message);
            return View(vm);
        }

        return RedirectToAction(nameof(Index), new { jenis, tahun });
    }

    [Route("[area]/[controller]/{jenis}/{tahun:int}/[action]/{id:int}")]
    public async Task<IActionResult> EditDetailRAPBJ(Jenis jenis, int tahun, int id)
    {
        var rTahun = Tahun.Create(tahun);
        if (rTahun.IsFailure) return BadRequest();

        var rapbj = await _repositoriRAPBJ.Get(rTahun.Value);
        if (rapbj is null) return NotFound();

        var detailRAPBJ = rapbj.DaftarDetailRAPBJ.FirstOrDefault(d => d.Akun.Id == id);
        if (detailRAPBJ is null) return NotFound();

        return View(new EditDetailRAPBJVM
        {
            Tahun = tahun,
            Jenis = jenis,
            IdAkun = id,
            HargaSatuan = detailRAPBJ.HargaSatuan,
            Satuan = detailRAPBJ.Satuan,
            Volume = detailRAPBJ.Volume,
        });
    }

    [HttpPost]
    [Route("[area]/[controller]/{jenis}/{tahun:int}/[action]")]
    public async Task<IActionResult> EditDetailRAPBJPOST(
        [FromRoute] Jenis jenis,
        [FromRoute] int tahun,
        [FromForm] EditDetailRAPBJVM vm)
    {
        if (!ModelState.IsValid)
            return View(vm);

        if (jenis != vm.Jenis || tahun != vm.Tahun) return BadRequest();

        var command = new EditDetailRAPBJCommand(tahun, vm.IdAkun, vm.Volume, vm.Satuan, vm.HargaSatuan);
        var result = await _sender.Send(command);
        if (result.IsFailure)
        {
            ModelState.AddModelError(string.Empty, result.Error.Message);
            return View(vm);
        }

        return RedirectToAction(nameof(Index), new { jenis, tahun });
    }

    [HttpPost]
    [Route("[area]/[controller]/{jenis}/{tahun:int}/[action]/{id:int}")]
    public async Task<IActionResult> HapusDetailRAPBJ(Jenis jenis, int tahun, int id)
    {
        var rTahun = Tahun.Create(tahun);
        if (rTahun.IsFailure) return BadRequest();

        var command = new DeleteDetailRAPBJCommand(tahun, id);
        var result = await _sender.Send(command);

        if (result.IsFailure)
        {
            _notificationService.AddNotification(new ToastrNotification
            {
                Title = "Hapus Gagal",
                Message = result.Error.Message,
                Type = ToastrNotificationType.Error
            });
        }
        else
        {
            _notificationService.AddNotification(new ToastrNotification
            {
                Title = "Hapus Berhasil",
                Message = "Akun berhasil dihapus dari RAPBJ",
                Type = ToastrNotificationType.Success
            });
        }

        return RedirectToAction(nameof(Index), new { jenis, tahun });
    }

    [HttpPost]
    [Route("[area]/[controller]/{jenis}/{tahun:int}/[action]")]
    public async Task<IActionResult> TambahRAPBJ(Jenis jenis, int tahun)
    {
        var command = new CreateRAPBJCommand(tahun);
        var result = await _sender.Send(command);

        if (result.IsFailure)
        {
            _notificationService.AddNotification(new ToastrNotification
            {
                Title = "Tambah RAPBJ Gagal",
                Message = result.Error.Message,
                Type = ToastrNotificationType.Error
            });
        }
        else
        {
            _notificationService.AddNotification(new ToastrNotification
            {
                Title = "Tambah RAPBJ Berhasil",
                Message = $"RAPBJ Tahun {tahun} berhasil dibuat",
                Type = ToastrNotificationType.Success
            });
        }

        return RedirectToAction(nameof(Index), new { jenis, tahun });
    }

    [HttpPost]
    [Route("[area]/[controller]/{jenis}/{tahun:int}/[action]")]
    public async Task<IActionResult> TambahSemuaAkun(Jenis jenis, int tahun)
    {
        var command = new AddAllAkunCommand(tahun);
        var result = await _sender.Send(command);

        if (result.IsFailure)
        {
            _notificationService.AddNotification(new ToastrNotification
            {
                Title = "Tambah Semua Akun ke RAPBJ Gagal",
                Message = result.Error.Message,
                Type = ToastrNotificationType.Error
            });
        }
        else
        {
            _notificationService.AddNotification(new ToastrNotification
            {
                Title = "Tambah Semua Akun ke RAPBJ Berhasil",
                Message = $"Semua akun tahun {tahun} berhasil dimasukkan ke RAPBJ tahun {tahun}",
                Type = ToastrNotificationType.Success
            });
        }

        return RedirectToAction(nameof(Index), new { jenis, tahun });
    }

    [HttpPost]
    [Route("[area]/[controller]/{jenis}/{tahun:int}/[action]")]
    public async Task<IActionResult> HapusRAPBJ(Jenis jenis, int tahun)
    {
        var command = new DeleteRAPBJCommand(tahun);
        var result = await _sender.Send(command);

        if (result.IsFailure)
        {
            _notificationService.AddNotification(new ToastrNotification
            {
                Title = $"Hapus RAPBJ tahun {tahun} Gagal",
                Message = result.Error.Message,
                Type = ToastrNotificationType.Error
            });
        }
        else
        {
            _notificationService.AddNotification(new ToastrNotification
            {
                Title = $"Hapus RAPBJ tahun {tahun} Berhasil",
                Message = $"RAPBJ tahun {tahun} berhasil dihapus",
                Type = ToastrNotificationType.Success
            });
        }

        return RedirectToAction(nameof(Index), new { jenis, tahun });
    }
}

src/SIKeuanganGMITLanudPenfui/SIKeuanganGMITLanudPenfui.Web/Controllers/LaporanController.cs
using Microsoft.AspNetCore.Mvc;
using SIKeuanganGMITLanudPenfui.Domain.Enums;
using SIKeuanganGMITLanudPenfui.Domain.Repositories;
using SIKeuanganGMITLanudPenfui.Domain.ValueObjects;
using SIKeuanganGMITLanudPenfui.Web.Dashboard.Models.LaporanModels;

namespace SIKeuanganGMITLanudPenfui.Web.Controllers;

public class LaporanController : Controller
{
    private readonly IRepositoriRAPBJ _repositoriRAPBJ;
    private readonly IRepositoriJenisAkun _repositoriJenisAkun;
    private readonly IRepositoriTransaksi _repositoriTransaksi;
    private readonly IRepositoriKas _repositoriKas;

    public LaporanController(
        IRepositoriRAPBJ repositoriRAPBJ,
        IRepositoriJenisAkun repositoriJenisAkun,
        IRepositoriTransaksi repositoriTransaksi,
        IRepositoriKas repositoriKas)
    {
        _repositoriRAPBJ = repositoriRAPBJ;
        _repositoriJenisAkun = repositoriJenisAkun;
        _repositoriTransaksi = repositoriTransaksi;
        _repositoriKas = repositoriKas;
    }

    public async Task<IActionResult> Index()
    {
        var daftarTransaksi = await _repositoriTransaksi.GetAll();
        var daftarKas = await _repositoriKas.GetAll();

        return View(new IndexVM { DaftarTransaksi = daftarTransaksi, DaftarKas = daftarKas});
    }
}

src/SIKeuanganGMITLanudPenfui/SIKeuanganGMITLanudPenfui.Web/ViewComponents/ToastrViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SIKeuanganGMITLanudPenfui.Web.Models;
using SIKeuanganGMITLanudPenfui.Web.Services.Toastr;

namespace SIKeuanganGMITLanudPenfui.Web.ViewComponents;

public class ToastrViewComponent : ViewComponent
{
    private readonly IToastrNotificationService _notificationService;

    public ToastrViewComponent(IToastrNotificationService notificationService)
    {
        _notificationService = notificationService;
    }

    public IViewComponentResult Invoke(ToastrOptions globalOptions)
    {
        string globalOptionsJson = JsonConvert.SerializeObject(globalOptions, new JsonSerializerSettings
        {
            NullValueHandling = NullValueHandling.Ignore,
            Formatting = Formatting.Indented,
        });
        return View((globalOptionsJson, _notificationService.GetNotificationJson()));
    }
}

src/SIKeuanganGMITLanudPenfui/SIKeuanganGMITLanudPenfui.Web/Areas/Dashboard/Views/Shared/_BreadcrumbPartial.cshtml
<nav aria-label="breadcrumb">
    <ol id="breadcrumb" class="breadcrumb">
    </ol>
</nav>

src/SIKeuanganGMITLanudPenfui/SIKeuanganGMITLanudPenfui.Web/Areas/Dashboard/Views/Shared/_Layout.cshtml
@using SIKeuanganGMITLanudPenfui.Web.Models
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistem Keuangan GMIT Lanud Penfui</title>
    <link rel="stylesheet" href="~/css/app.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/datatables/datatables.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/dashboard.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/component.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/theme.css" asp-append-version="true" />
    @*     <link rel="stylesheet" href="~/SIKeuanganGMITLanudPenfui.Web.styles.css" asp-append-version="true" /> *@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <!-- Inisialisasi Owl Carousel -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css" />
    <!-- Akhir Inisialisasi Owl Carousel -->
</head>
<body>
    
    <div id="app">
        <div class="main-wrapper main-wrapper-1">
            <partial name="_NavbarPartial" />
            <partial name="_SidebarPartial" />

            <div class="main-content">
                <div class="section">
                    <main role="main">
                        @RenderBody()
                    </main>
                </div>
                   
                <partial name="_ModalPartial" />
                <partial name="_SettingsthemePartial" />
            </div>
        </div>        
    </div>
   
    <script src="~/js/app.min.js" asp-append-version="true"></script>
    <script src="~/lib/datatables/datatables.min.js" asp-append-version="true"></script>
    <script src="~/lib/datatables/export-tables/dataTables.buttons.min.js" asp-append-version="true"></script>
    <script src="~/lib/datatables/export-tables/buttons.flash.min.js" asp-append-version="true"></script>
    <script src="~/lib/datatables/export-tables/buttons.print.min.js" asp-append-version="true"></script>
    <script src="~/lib/datatables/export-tables/jszip.min.js" asp-append-version="true"></script>
    <script src="~/lib/datatables/export-tables/pdfmake.min.js" asp-append-version="true"></script>
    <script src="~/lib/datatables/export-tables/vfs_fonts.js" asp-append-version="true"></script>
    <script src="~/js/datatables.js" asp-append-version="true"></script>
    <script src="~/js/dashboard.js" asp-append-version="true"></script>

    <!-- Inisisalisasi Owl Carousel -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
    <!-- Akhir Inisisalisasi Chart.JS -->

    <script type="text/javascript">
        const matchLink = (linkHref, currentUrl, match) => {
            if (match === "partial") {
                return currentUrl.startsWith(linkHref);
            } else {
                return currentUrl === linkHref
            }
        }

        // LINK SIDEBAR ACTIVE
        document.addEventListener('DOMContentLoaded', () => {
            const links = document.querySelectorAll('.nav-link');

            const currentUrl = window.location.href;

            links.forEach(link => {
                if (matchLink(link.href, currentUrl, link.dataset.match)) {
                    link.parentNode.classList.add('active');
                } else {
                    link.parentNode.classList.remove('active');
                }
            });
        });
    </script>

    <script>
        let currentDeleteUrl = '';

        // Ketika tombol Hapus di tabel diklik
        $(document).on('click', '[data-target="#basicModal2"]', function () {
            // Ambil URL penghapusan dari data-url tombol
            currentDeleteUrl = $(this).data('url');
            $('#formModalHapus').attr('action', currentDeleteUrl);
        });

        // Ketika tombol Hapus di modal diklik
        // $('#modal-btn-hapus').on('click', function () {
        //     if (currentDeleteUrl) {
        //         $.ajax({
        //             url: currentDeleteUrl,
        //             type: 'POST',
        //             success: function (result) {
        //                 if (result.success) {
        //                     // Tutup modal
        //                     $('#basicModal2').modal('hide');
        //                     // Reload halaman atau hapus baris di tabel secara dinamis
        //                     location.reload();
        //                 } else {
        //                     alert(result.message || 'Terjadi kesalahan saat menghapus data.');
        //                 }
        //             },
        //             error: function () {
        //                 alert('Terjadi kesalahan saat menghapus data.');
        //             }
        //         });
        //     }
        // });
    </script>


    @{
        var globalOptions = new ToastrOptions
            {
                closeButton = true,
                progressBar = true,
                newestOnTop = true,
                preventDuplicates = false,
                timeOut = (int)TimeSpan.FromSeconds(5).TotalMilliseconds,
                extendedTimeOut = (int)TimeSpan.FromSeconds(5).TotalMilliseconds,
                showDuration = (int)TimeSpan.FromSeconds(0.5).TotalMilliseconds,
                hideDuration = (int)TimeSpan.FromSeconds(0.5).TotalMilliseconds,
                showEasing = Easings.Swing,
                hideEasing = Easings.Swing,
                showMethod = AnimationMethods.FadeIn,
                hideMethod = AnimationMethods.FadeOut,
                positionClass = PositionClasses.TopRight,
            };
    }

    <vc:toastr global-options=globalOptions></vc:toastr>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/SIKeuanganGMITLanudPenfui/SIKeuanganGMITLanudPenfui.Web/Areas/Dashboard/Views/Shared/_SidebarPartial.cshtml
@using SIKeuanganGMITLanudPenfui.Infrastructure.Authentication.Contracts
@inject ISignInManager SignInManager

@{
    var user = await SignInManager.GetUser();
}

<!-- SIDEBAR -->
<div class="main-sidebar sidebar-style-2">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
            <a href="">
                <i data-feather="user" class="header-logo"></i>
                <span class="logo-name">Lanud<span>ElTari</span></span>
            </a>
        </div>
        <ul class="sidebar-menu">
            <li class="menu-header">Dashboard</li>
            <li>
                <a asp-area="Dashboard" asp-controller="Home" asp-action="Index" data-match="all" class="nav-link"><i data-feather="monitor"></i><span>Dashboard</span></a>
            </li>

            @if (user!.Role == UserRoles.Bendahara)
            {
                <li class="menu-header">Akun</li>
                <li><a asp-area="Dashboard" asp-controller="Akun" asp-action="Penerimaan" data-match="partial" class="nav-link"><i data-feather="package"></i><span>Penerimaan</span></a></li>
                <li><a asp-area="Dashboard" asp-controller="Akun" asp-action="Belanja" data-match="partial" class="nav-link"><i data-feather="shopping-bag"></i><span>Belanja</span></a></li>

                <li class="menu-header">RAPBJ</li>
                <li><a asp-area="Dashboard" asp-controller="RAPBJ" asp-action="Index" asp-route-jenis="@Jenis.Penerimaan" data-match="partial" class="nav-link"><i data-feather="package"></i><span>Penerimaan</span></a></li>
                <li><a asp-area="Dashboard" asp-controller="RAPBJ" asp-action="Index" asp-route-jenis="@Jenis.Belanja" data-match="partial" class="nav-link"><i data-feather="shopping-bag"></i><span>Belanja</span></a></li>
            }

            <li class="menu-header">Realisasi</li>
            <li><a asp-area="Dashboard" asp-controller="Realisasi" asp-action="@nameof(RealisasiController.Kas)" data-match="partial" class="nav-link"><i data-feather="shopping-bag"></i><span>Kas</span></a></li>
            <li><a asp-area="Dashboard" asp-controller="Realisasi" asp-action="@nameof(RealisasiController.Transaksi)" asp-route-jenis="@Jenis.Penerimaan" data-match="partial" class="nav-link"><i data-feather="package"></i><span>Penerimaan</span></a></li>
            <li><a asp-area="Dashboard" asp-controller="Realisasi" asp-action="@nameof(RealisasiController.Transaksi)" asp-route-jenis="@Jenis.Belanja" data-match="partial" class="nav-link"><i data-feather="shopping-bag"></i><span>Belanja</span></a></li>
            <li><a asp-area="Dashboard" asp-controller="Realisasi" asp-action="@nameof(RealisasiController.Panjar)" data-match="partial" class="nav-link"><i data-feather="shopping-bag"></i><span>Panjar</span></a></li>

            <li class="menu-header">Laporan</li>
            <li><a asp-area="Dashboard" asp-controller="Laporan" asp-action="@nameof(LaporanController.LaporanMingguan)" data-match="partial" class="nav-link"><i data-feather="file-text"></i><span>Laporan Harian</span></a></li>
            <li><a asp-area="Dashboard" asp-controller="Laporan" asp-action="@nameof(LaporanController.BKU)" asp-route-bulan="1" data-match="partial" class="nav-link"><i data-feather="file-text"></i><span>BKU</span></a></li>
            <li><a asp-area="Dashboard" asp-controller="Laporan" asp-action="@nameof(LaporanController.RekaptulasiTahunan)" data-match="partial" class="nav-link"><i data-feather="calendar"></i><span>Rekapitulasi Tahunan</span></a></li>
            <li><a asp-area="Dashboard" asp-controller="Laporan" asp-action="@nameof(LaporanController.RAPBJ)" data-match="partial" class="nav-link"><i data-feather="calendar"></i><span>RAPBJ</span></a></li>

            <li class="menu-header">Lainnya</li>
            <li><a asp-area="Dashboard" asp-controller="FeedBack" asp-action="@nameof(FeedBackController.Index)" data-match="partial" class="nav-link"><i data-feather="sliders"></i><span>Umpan Balik</span></a></li>
            <li><a asp-area="Dashboard" asp-controller="InformasiGereja" asp-action="@nameof(InformasiGerejaController.Index)" data-match="partial" class="nav-link"><i data-feather="sliders"></i><span>Informasi Gereja</span></a></li>
            @*<li><a href="" data-match="partial" class="nav-link"><i data-feather="settings"></i><span>Pengaturan</span></a></li>
            <li><a href="" data-match="partial" class="nav-link"><i data-feather="mail"></i><span>Laporan</span></a></li> *@
        </ul>
    </aside>
</div>